const products=[
{id:1,name:'Morrow Bed',category:'BED',price:'1,280,000원',image:'assets/best1.jpg'},
{id:2,name:'Layer Bed',category:'BED',price:'980,000원',image:'assets/bed3.jpg'},
{id:3,name:'Frame Chair',category:'CHAIR',price:'320,000원',image:'assets/chair8.jpg'},
{id:4,name:'Soft Lounge',category:'CHAIR',price:'460,000원',image:'assets/chair2.jpg'},
{id:5,name:'Line Table',category:'TABLE',price:'540,000원',image:'assets/table4.jpg'},
{id:6,name:'Oak Dining',category:'TABLE',price:'720,000원',image:'assets/table7.jpg'},
{id:7,name:'Calm Bed',category:'BED',price:'1,120,000원',image:'assets/bed5.jpg'},
{id:8,name:'Daily Chair',category:'CHAIR',price:'290,000원',image:'assets/chair5.jpg'}];
let filter='ALL',saved=[],selected=null;const grid=document.querySelector('.product-grid'),count=document.querySelector('.saved-open span'),modal=document.querySelector('.product-modal'),toast=document.querySelector('.toast');
function render(){grid.innerHTML=products.filter(p=>filter==='ALL'||p.category===filter).map(p=>`<article><button class="product-image" data-view="${p.id}" aria-label="${p.name} 자세히 보기"><img src="${p.image}" alt="${p.name}" loading="lazy"><i>VIEW ↗</i></button><div class="product-meta"><div><span>${p.category}</span><h3>${p.name}</h3><p>${p.price}</p></div><button class="${saved.includes(p.id)?'active':''}" data-save="${p.id}" aria-label="${p.name} 찜하기">${saved.includes(p.id)?'♥':'♡'}</button></div></article>`).join('');count.textContent=saved.length;}
function note(text){toast.textContent=text;toast.classList.add('show');clearTimeout(note.timer);note.timer=setTimeout(()=>toast.classList.remove('show'),1800)}
function toggle(id){saved=saved.includes(id)?saved.filter(item=>item!==id):[...saved,id];render();if(selected?.id===id)document.querySelector('.modal-save').textContent=saved.includes(id)?'♥ SAVED':'♡ WISHLIST';note(saved.includes(id)?'위시리스트에 담았어요.':'위시리스트에서 제외했어요.');}
function openProduct(id){selected=products.find(p=>p.id===id);modal.querySelector('img').src=selected.image;modal.querySelector('img').alt=selected.name;modal.querySelector('span').textContent=selected.category;modal.querySelector('h2').textContent=selected.name;modal.querySelector('.modal-price').textContent=selected.price;modal.querySelector('.modal-save').textContent=saved.includes(id)?'♥ SAVED':'♡ WISHLIST';modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('locked')}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('locked');selected=null}
document.querySelectorAll('.filters button').forEach(btn=>btn.addEventListener('click',()=>{filter=btn.dataset.filter;document.querySelectorAll('.filters button').forEach(b=>b.classList.toggle('active',b===btn));render()}));grid.addEventListener('click',e=>{const view=e.target.closest('[data-view]'),save=e.target.closest('[data-save]');if(view)openProduct(Number(view.dataset.view));if(save)toggle(Number(save.dataset.save))});document.querySelectorAll('[data-room]').forEach(btn=>btn.addEventListener('click',()=>{filter=btn.dataset.room==='LIVING'?'CHAIR':btn.dataset.room;document.querySelector('#collection').scrollIntoView();document.querySelectorAll('.filters button').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));render()}));modal.querySelector('.modal-close').addEventListener('click',closeModal);modal.querySelector('.modal-bg').addEventListener('click',closeModal);modal.querySelector('.modal-save').addEventListener('click',()=>selected&&toggle(selected.id));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});const mobile=document.querySelector('.mobile-nav');document.querySelector('.menu').addEventListener('click',()=>{mobile.classList.add('open');document.body.classList.add('locked')});mobile.querySelector('button').addEventListener('click',()=>{mobile.classList.remove('open');document.body.classList.remove('locked')});mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobile.classList.remove('open');document.body.classList.remove('locked')}));render();setTimeout(()=>document.querySelector('.loader').classList.add('hidden'),2200);
